language: objective-c
sudo: false
matrix:
  include:
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode8.1
    - os: osx
      osx_image: xcode8.2

before_script:
  - export LANG=en_US.UTF-8
install: bundle
script:
  - csrutil status
  - git submodule update --init --recursive
  - bundle exec rake build_test_dumper spec
