language: objective-c
sudo: true
matrix:
  include:
      - os: osx
        osx_image: xcode8

before_script:
  - export LANG=en_US.UTF-8
install: bundle
script:
  - git submodule update --init --recursive
  - bundle exec rake build_test_dumper spec
